spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartdriving
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8083}/auth/realms/master
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  email:

sms:
  twilio:
    account-sid:
    auth-token:
    phone-number:

vignette:
  url: https://www.erovinieta.ro/vgncheck/api/findVignettes








